// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v5.28.3
// source: example.proto

/* eslint-disable */

export const protobufPackage = "example";

export const EXAMPLE_PACKAGE_NAME = "example";
